#!/bin/bash

set -ex

apt-get update -qq
apt-get install -y -q build-essential libssl-dev libffi-dev nginx python-dev python-pip wget
pip install gsutil path.py

VERSION=`config-get version`
ARCH=`dpkg --print-architecture`
# List the files available for the version and architecture error if none exist.
gsutil ls gs://kubernetes-release/release/$VERSION/bin/linux/$ARCH/

# Open port 8080 for nginx.
open-port 8080
